yhcomments:
    resource: "@yhcommentsBundle/Resources/config/routing.yml"
    prefix:   /

yhpost:
    resource: "@yhpostBundle/Resources/config/routing.yml"
    prefix:   /

yhblog:
    resource: "@yhblogBundle/Resources/config/routing.yml"
    prefix:   /

#iknsa_app:
#    resource: "@IKNSAAppBundle/Resources/config/routing.yml"
#    prefix:   /

#crud:
#    resource: "@CrudBundle/Resources/config/routing.yml"
#    prefix:   /

# app/config/routing.yml
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"