<?php

namespace CrudBundle\Repository;

/**
 * FriendRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FriendRepository extends \Doctrine\ORM\EntityRepository
{
}
